# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslareturn',
            name='return_amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
