# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20170218_1553'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teslareturn',
            table='tesla_return',
        ),
    ]
